version: '3.8'

services:
  db:
    image: mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smiledb
    container_name: mysql-smiledb
    ports:
      - 3306:3306
    volumes:
      - schemas:/var/lib/mysql

volumes:
  schemas:
