server:
  port: 8080
spring:
  application:
    name: Smile Clinic
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
logging:
  level:
    org:
      hibernate.SQL: debug
      springframework:
        security: DEBUG
    com:
      smile:
        clinic:
          smile_clinic:
            infrastructure:
              adapters:
                config:
                  security: DEBUG  # Enables debug logs for your security configuration and filter
security:
  jwt:
    expiration-minutes: 30
    secret-key: N3VZbDMwa0V3Z2RIQ1lpM0xoWlR0dEF3SmV6dDZvYkM=


