server:
  port: 8080
spring:
  application:
    name: Smile Clinic
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
logging:
  level:
    org.hibernate.SQL: debug
